CREATE TABLE USERS(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  FIRSTNAME VARCHAR(40) NOT NULL,
  LASTNAME VARCHAR(40),  
  EMAIL VARCHAR(100) NOT NULL,
  MOBILE_NO VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);


