ALTER TABLE USERS ADD COLUMN PASSWORD VARCHAR(100) NOT NULL DEFAULT 'osiafoiefe3k';

CREATE TABLE AUTHORITY(  
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_AUTHORITY(  
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USER_ID INTEGER NOT NULL,
  AUTHORITY_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(ID)
);

CREATE TABLE TASK(  
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TITLE VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(200),
  CREATED_BY INT NOT NULL,
  LAST_MODIFIED_BY INT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
  FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES USERS(ID)
);

INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, MOBILE_NO, PASSWORD) VALUES ('admin', 'admin', 'admin@boot.com', '9999999999', '$2a$10$Oxm9zeWvkD9oa5yeZJ5T5eZhM4VFcrzcrwtYfQJoBzlkqmkeiZo.2');
INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL, MOBILE_NO, PASSWORD) VALUES ('user', 'user', 'user@boot.com', '9898989898', '$2a$10$pKqV1oABeq01SemLGufQ/.bHO4W0olykC.KQ.99rKhjHQ0RQt4e7m');

INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ANONYMOUS');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) 
  (select u.id, a.id from USERS u , AUTHORITY a where u.email = 'admin@boot.com' and a.name = 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) 
  (select u.id, a.id from USERS u , AUTHORITY a where u.email = 'admin@boot.com' and a.name = 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) 
  (select u.id, a.id from USERS u , AUTHORITY a where u.email = 'user@boot.com' and a.name = 'ROLE_USER');
